### PR TITLE
 Fix: `yarn chain-of-trust cleanup` now removes prometheus certs

### LINKED ISSUE #191: yarn chain-of-trust cleanup issues
The yarn chain-of-trust cleanup commands doesn't clean the prometheus certs.

### PR DESCRIPTION
**Pull request by Msarawan**
The `yarn chain-of-trust cleanup` command was not cleaning up the prometheus-cert Certificate and Secret resources, leaving them behind in the operator namespace after cleanup. 

fixes: [issue#191](https://github.com/arkmq-org/activemq-artemis-self-provisioning-plugin/issues/191)

### CODE REVIEW

File: scripts/chain-of-trust.js [hunk 1]
```diff
@@ -207,6 +208,15 @@ async function cleanup() {
...
 
+    // Delete prometheus certificate and secret
+    console.log(`  Deleting Prometheus certificate from ${namespace}...`);
+    await execAsync(
+      `kubectl delete certificate ${resourceNames.prometheusCert} -n ${namespace} --ignore-not-found=true`,
+    );
+    await execAsync(
+      `kubectl delete secret ${resourceNames.prometheusCert} -n ${namespace} --ignore-not-found=true`,
+    );
+
```
Comment (lavocatt) [inline scripts/chain-of-trust.js:215]: The problem is that, there might be prometheus certs hanging around in other namespaces than the operator one.
The thing I'd like to see in the cleanup of the prometheus cert is to follow the  pattern for   `await deleteCertificatePattern('broker-cert');` instead.

**Review by lavocatt — APPROVED** [review]
LGTM! Thanks
